### ISSUE TITLE
tr_golds not found

### ISSUE THREAD

**Issue by muschellij2** [muschellij2/imaging_in_r#4]
In `ms_lesion_segmentation` you define 

```r
tr_golds1 = lapply(tr_files, function(x) readnii(x["mask1"]))
tr_golds2 = lapply(tr_files, function(x) readnii(x["mask2"]))
```
but later use `tr_golds`.  It still runs because you cached it, but this needs to be fixed.

**Comment by kalinn** [comment]
Right.  I changed it to incorporate both manual segmentations in the calculation of dice, but I didn't want to have to retrain the model (I think we trained using only mask 2).  I will update `oasis_train_dataframe` to use tr_golds2

**Comment by muschellij2** [comment]
Confirmed we used mask2
