### ISSUE TITLE
Error in runing  fslbet_robust function

### ISSUE THREAD

**Issue by xuesongle** [muschellij2/imaging_in_r#6]

**Comment by xuesongle** [comment]
@muschellij2 or it might be a shell issue as indicated in [here](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;36126b57.1709). But I checked the /usr/local/fsl/bin/fsl_sub. The first line is already in #!/bin/bash. and type echo $0 in any terminal, it also $ echo $0
bash.

**Comment by xuesongle** [comment]
@muschellij2 , once I changed the input file to [SUBJ0001-01-MPRAGE.nii.gz](https://github.com/muschellij2/Neurohacking/blob/master/Basic_Data_Manipulations/Kirby21/SUBJ0001-01-MPRAGE.nii.gz), then it works. So it seems like the error exist in how the nifti file is made but still not sure how to fix it.

**Comment by muschellij2** [comment]
Sorry - I don't have time for this at the moment.  I will look into it in the next month or so.

**Comment by muschellij2** [comment]
This should be fixed with the new version of `fslr`:

```r
devtools::install_github("muschellij2/fslr")
```

**Comment by xuesongle** [comment]
@muschellij2, after removing the old package and installing fslr with devtools::install_github("muschellij2/fslr"), then it works. Thanks, John.
